# Generated by Django 4.1.6 on 2023-02-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='homepage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.author'),
        ),
    ]
