# Generated by Django 4.1.6 on 2023-02-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_name_author_name_homepage_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='comapny_url',
            new_name='company_url',
        ),
    ]
